[package]
name = "demo"
version = "0.0.0"
description  = "Library demo"
authors = ["Sean Fisk <sean@seanfisk.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
log = "0.4"

[dependencies.clap-logging]
path = ".."
